#include "bsp_IdleIO.h"

void BSP_IdleIO_Init(void)
{
	RCC_EnableAPB2PeriphClk(RCC_APB2_PERIPH_AFIO, ENABLE);
	RCC_EnableAPB2PeriphClk(RCC_APB2_PERIPH_GPIOA, ENABLE);
	RCC_EnableAPB2PeriphClk(RCC_APB2_PERIPH_GPIOB, ENABLE);
	RCC_EnableAPB2PeriphClk(RCC_APB2_PERIPH_GPIOC, ENABLE);
	RCC_EnableAPB2PeriphClk(RCC_APB2_PERIPH_GPIOD, ENABLE);	
	AFIO->RMP_CFG = 0x02000000;//关闭 JTAG -DP ，启用 SW -DP 
	//所有端口最低刷新频率,输出,低电平
	GPIOA->PH_CFG = 0x11111111;
	GPIOB->PL_CFG = 0x11111111;
	GPIOC->PH_CFG = 0x11111111;
	GPIOD->PL_CFG = 0x11111111;
	GPIOA->POD = 0;
	GPIOB->POD = 0;
	GPIOC->POD = 0;
	GPIOD->POD = 0;
	
}




